/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import type { MyContextType } from './src/modules/server__gql-model/context';
import type { Decimal } from '@prisma/client/runtime';

declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    model: NexusPrisma<TypeName, 'model'>;
    crud: any;
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  DateTimeFilter: {
    // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
  };
  DecimalFilter: {
    // input type
    equals?: NexusGenScalars['Decimal'] | null; // Decimal
    gt?: NexusGenScalars['Decimal'] | null; // Decimal
    gte?: NexusGenScalars['Decimal'] | null; // Decimal
    in?: Array<NexusGenScalars['Decimal'] | null> | null; // [Decimal]
    lt?: NexusGenScalars['Decimal'] | null; // Decimal
    lte?: NexusGenScalars['Decimal'] | null; // Decimal
    not?: NexusGenInputs['DecimalFilter'] | null; // DecimalFilter
    notIn?: Array<NexusGenScalars['Decimal'] | null> | null; // [Decimal]
  };
  IdFilter: {
    // input type
    equals?: string | null; // ID
    gt?: string | null; // ID
    gte?: string | null; // ID
    in?: Array<string | null> | null; // [ID]
    lt?: string | null; // ID
    lte?: string | null; // ID
    not?: NexusGenInputs['IdFilter'] | null; // IdFilter
    notIn?: Array<string | null> | null; // [ID]
  };
  IntFilter: {
    // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['IntFilter'] | null; // IntFilter
    notIn?: Array<number | null> | null; // [Int]
  };
  NetworkEnumFilter: {
    // input type
    equals?: NexusGenEnums['Network'] | null; // Network
    in?: Array<NexusGenEnums['Network'] | null> | null; // [Network]
    not?: NexusGenInputs['NetworkEnumFilter'] | null; // NetworkEnumFilter
    notIn?: Array<NexusGenEnums['Network'] | null> | null; // [Network]
  };
  StringFilter: {
    // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['StringFilterMode'] | null; // StringFilterMode
    not?: NexusGenInputs['StringFilter'] | null; // StringFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  };
  TokenWhereInput: {
    // input type
    AND?: Array<NexusGenInputs['TokenWhereInput'] | null> | null; // [TokenWhereInput]
    NOT?: Array<NexusGenInputs['TokenWhereInput'] | null> | null; // [TokenWhereInput]
    OR?: Array<NexusGenInputs['TokenWhereInput'] | null> | null; // [TokenWhereInput]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    decimals?: NexusGenInputs['IntFilter'] | null; // IntFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    logoUri?: NexusGenInputs['StringFilter'] | null; // StringFilter
    network?: NexusGenInputs['NetworkEnumFilter'] | null; // NetworkEnumFilter
    symbol?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  };
}

export interface NexusGenEnums {
  Network: 'BSC' | 'ETHEREUM' | 'POLYGON';
  StringFilterMode: 'default' | 'insensitive';
}

export interface NexusGenScalars {
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  DateTime: Date;
  Decimal: Decimal;
}

export interface NexusGenObjects {
  ForwardPaginationPageInfo: {
    // root type
    endCursor: string; // String!
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string; // String!
  };
  Query: {};
  Token: {
    // root type
    address: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    decimals: number; // Int!
    id: string; // String!
    logoUri?: string | null; // String
    network: NexusGenEnums['Network']; // Network!
    symbol: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  };
  TokensConnection: {
    // root type
    edges: NexusGenRootTypes['TokensConnectionEdges'][]; // [TokensConnectionEdges!]!
    pageInfo: NexusGenRootTypes['ForwardPaginationPageInfo']; // ForwardPaginationPageInfo!
    totalCount: number; // Int!
  };
  TokensConnectionEdges: {
    // root type
    cursor: string; // String!
    node: NexusGenRootTypes['Token']; // Token!
  };
}

export interface NexusGenInterfaces {}

export interface NexusGenUnions {}

export type NexusGenRootTypes = NexusGenObjects;

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums;

export interface NexusGenFieldTypes {
  ForwardPaginationPageInfo: {
    // field return type
    endCursor: string; // String!
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string; // String!
  };
  Query: {
    // field return type
    token: NexusGenRootTypes['Token']; // Token!
    tokens: NexusGenRootTypes['TokensConnection']; // TokensConnection!
  };
  Token: {
    // field return type
    address: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    decimals: number; // Int!
    id: string; // String!
    logoUri: string | null; // String
    network: NexusGenEnums['Network']; // Network!
    symbol: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  };
  TokensConnection: {
    // field return type
    edges: NexusGenRootTypes['TokensConnectionEdges'][]; // [TokensConnectionEdges!]!
    pageInfo: NexusGenRootTypes['ForwardPaginationPageInfo']; // ForwardPaginationPageInfo!
    totalCount: number; // Int!
  };
  TokensConnectionEdges: {
    // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Token']; // Token!
  };
}

export interface NexusGenFieldTypeNames {
  ForwardPaginationPageInfo: {
    // field return type name
    endCursor: 'String';
    hasNextPage: 'Boolean';
    hasPreviousPage: 'Boolean';
    startCursor: 'String';
  };
  Query: {
    // field return type name
    token: 'Token';
    tokens: 'TokensConnection';
  };
  Token: {
    // field return type name
    address: 'String';
    createdAt: 'DateTime';
    decimals: 'Int';
    id: 'String';
    logoUri: 'String';
    network: 'Network';
    symbol: 'String';
    updatedAt: 'DateTime';
  };
  TokensConnection: {
    // field return type name
    edges: 'TokensConnectionEdges';
    pageInfo: 'ForwardPaginationPageInfo';
    totalCount: 'Int';
  };
  TokensConnectionEdges: {
    // field return type name
    cursor: 'String';
    node: 'Token';
  };
}

export interface NexusGenArgTypes {
  Query: {
    token: {
      // args
      id: string; // ID!
    };
    tokens: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      where?: NexusGenInputs['TokenWhereInput'] | null; // TokenWhereInput
    };
  };
}

export interface NexusGenAbstractTypeMembers {}

export interface NexusGenTypeInterfaces {}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false;
    resolveType: true;
    __typename: false;
  };
};

export interface NexusGenTypes {
  context: MyContextType;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes:
    | NexusGenTypes['inputNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['scalarNames'];
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes'];
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {}
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {}
  interface NexusGenPluginSchemaConfig {}
  interface NexusGenPluginArgConfig {}
}
